const CACHE='creature-league-v39';
const FILES=[...['ember','crystal','pearl','feather','gate-blue','gate-gold','burst-star','burst-splash',...['water','lightning','stone','fire','whirl','beam','wave','hypno','leaf','wind','spear','fireball','spark'].map(k=>'shot-'+k)].map(n=>'./art/gen/prop-'+n+'.png'),...['coast','wind','sea','fire','mirror','castle'].flatMap(k=>['./art/gen/prop-rock-'+k+'.png','./art/gen/prop-rubble-'+k+'.png']),'./','./index.html','./style.css','./app.js','./core.js','./art.js','./audio.js','./icon.svg','./manifest.webmanifest','./vendor/rig.js','./art/2026-09-15__Coastal-Arena__Background__v01__FINAL.png',...['water','storm','canyon','volcano','light','quake','nebula','forest','crystal'].map(n=>'./art/gen/card-'+n+'.jpg'),'./art/gen/music-battle.mp3','./art/gen/music-map.mp3',...['maimi','havzuk','slauz','lohatan','tehomon','zikuk','retetoz','tzlilon','shorshu','galgalor','windguard','seaguard','fireguard','zoharon','kokhavit'].flatMap(id=>['rig.json','clips.json','parts.png'].map(ext=>'./art/'+id+'.'+ext))];
FILES.push('./art/gen/card-back.jpg',...['sfx-card-flip','sfx-join-fanfare','voice-wild-battle','voice-victory','voice-new-creature','voice-new-card'].map(n=>'./art/gen/'+n+'.mp3'));
FILES.push('./theme.css','./phone.css','./art/gen/frame.png',...['wind','sea','fire','mirror','castle'].map(n=>'./art/gen/arena-'+n+'.jpg'),...['after-castle','after-castle-gate','after-fire-free','after-fire-free2','after-fire-guard','after-fire-mission','after-mirror-free','after-mirror-guard','after-sea-free','after-sea-free2','after-sea-guard','after-sea-mission','after-wind-free','after-wind-free2','after-wind-guard','after-wind-mission','castle','castle-door','castle-gate','fire-free','fire-free2','fire-guard','fire-mission','hello','mirror-free','mirror-guard','sea-free','sea-free2','sea-guard','sea-mission','wind-free','wind-free2','wind-guard','wind-mission'].map(n=>'./art/gen/voice-shadow-'+n+'.mp3'),'./story.js',...['map.jpg','ron.png','little-shadow.png','egg.png','mask-shard.png'].map(n=>'./art/gen/story-'+n));
FILES.push('./art/heebo-regular.ttf','./art/heebo-bold.ttf','./art/heebo-black.ttf','./upgrades.js');
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(FILES)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('creature-league-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{
  if(event.request.method!=='GET'||new URL(event.request.url).origin!==self.location.origin)return;
  event.respondWith(fetch(event.request,{cache:'no-cache'}).then(response=>{if(response.ok&&response.status===200){const copy=response.clone();event.waitUntil(caches.open(CACHE).then(cache=>cache.put(event.request,copy)));}return response;}).catch(async()=>{const cached=await caches.match(event.request);if(cached)return cached;if(event.request.mode==='navigate')return caches.match('./index.html');return Response.error();}));
});
